- id: 1L
  side: left
  spray_height: 0.3
- id: 2L
  side: left
  spray_height: 0.6
- id: 3L
  side: left
  spray_height: 0.9
- id: 4L
  side: left
  spray_height: 1.2
- id: 5L
  side: left
  spray_height: 1.5
- id: 6L
  side: left
  spray_height: 1.8
- id: 7L
  side: left
  spray_height: 2.1

- id: 1R
  side: right
  spray_height: 0.3
- id: 2R
  side: right
  spray_height: 0.6
- id: 3R
  side: right
  spray_height: 0.9
- id: 4R
  side: right
  spray_height: 1.2
- id: 5R
  side: right
  spray_height: 1.5
- id: 6R
  side: right
  spray_height: 1.8
- id: 7R
  side: right
  spray_height: 2.1
