map_frame: vineyard
row_path_controller_id: FollowStraightPath
row_path_goal_checker_id: asb_goal_checker
row_path_progress_checker_id: simple_progress_checker
row_path_pose_distance: 0.1

alternate_rows: True
switch_direction: True
row_path_external_dist: 1.25
row_path_margin: 2.0
row_approach_margin: 1.0

rows:
  - row_id: row_0
    frame_id: vineyard
    start_point:
      x: 7.0
      y: 0.0
    end_point:
      x: 14.0
      y: 0.0
  - row_id: row_1
    frame_id: vineyard
    start_point:
      x: 7.0
      y: -2.5
    end_point:
      x: 14.0
      y: -2.5
#  - row_id: row_2
#    frame_id: vineyard
#    start_point:
#      x: 0.0
#      y: -5.0
#    end_point:
#      x: 15.0
#      y: -5.0
#  - row_id: row_3
#    frame_id: vineyard
#    start_point:
#      x: 0.0
#      y: -7.5
#    end_point:
#      x: 15.0
#      y: -7.5
