map_frame: vineyard

positioning_approach_planner_id: GridBased
positioning_approach_controller_id: FollowPath
positioning_approach_goal_checker_id: asb_goal_checker
positioning_approach_progress_checker_id: simple_progress_checker

straight_approach_controller_id: FollowPath
straight_approach_goal_checker_id: asb_goal_checker
straight_approach_progress_checker_id: simple_progress_checker
straight_approach_path_pose_distance: 0.1

row_path_controller_id: FollowStraightPath
row_path_goal_checker_id: asb_goal_checker
row_path_progress_checker_id: simple_progress_checker
row_path_pose_distance: 0.1

alternate_rows: True
switch_direction: True
row_path_external_dist: 1.25  # distance of inter-row path from row when navigating on the outside (as opposed to between two rows)
row_path_margin: 2.0  # distance of the positioning pose to the beginning of the rows
row_approach_margin: 1.0  # distance between the straightening and positioning approach pose

fan_velocity_target_rpm: 1200
fan_velocity_threshold_rpm: 800
max_canopy_width: 2.0
canopy_roi_x_1: -0.25
canopy_roi_x_2: 0.25
normalizing_velocity: 1.0
canopy_layer_bounds: [0.2, 0.6, 1.0, 1.4, 1.8, 2.2]

rows:
  - row_id: row_0
    frame_id: vineyard
    start_point:
      x: 7.0
      y: 0.0
    end_point:
      x: 14.0
      y: 0.0
  - row_id: row_1
    frame_id: vineyard
    start_point:
      x: 7.0
      y: -2.5
    end_point:
      x: 14.0
      y: -2.5
