- child_frame_id: sat_map
  frame_id: map
  x: 8.762481207901146
  y: 6.026659302413464
- child_frame_id: hedge
  frame_id: map
  x: 1.75
  y: 10.8
  qz: -0.573
  qw: 0.819
- child_frame_id: vineyard
  frame_id: map
  x: 14.6155
  y: -3.58378
  yaw: 1.9608