# For parameter descriptions, see https://github.com/cra-ros-pkg/robot_localization/blob/ros2/params/ekf.yaml
ekf_filter_map_odom:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true  # Recommended to use 2d mode for nav2 in mostly planar environments
    print_diagnostics: false
    debug: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: map  # publish the map->odom transform

    odom0: odometry/gps
    odom0_config: [
      true,  true,  false,  # x, y, z
      false, false, false,  # roll, pitch, yaw
      false, false, false,  # v_x, v_y, v_z
      false, false, false,  # v_roll, v_pitch, v_yaw
      false, false, false,  # a_x, a_y, a_z
    ]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    imu0: /imu
    imu0_config: [
      false, false, false,  # x, y, z
      false, false, false,  # roll, pitch, yaw
      false, false, false,  # v_x, v_y, v_z
      false, false, true,   # v_roll, v_pitch, v_yaw
      false, false, false,  # a_x, a_y, a_z
    ]
    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 5
    imu0_pose_rejection_threshold: 0.8                 # Note the difference in parameter names
    imu0_twist_rejection_threshold: 0.8                #
    imu0_linear_acceleration_rejection_threshold: 0.8  #

    # [ADVANCED] Some IMUs automatically remove acceleration due to gravity, and others don't. If yours doesn't, please set
    # this to true, and *make sure* your data conforms to REP-103, specifically, that the data is in ENU frame.
    imu0_remove_gravitational_acceleration: true

#    imu1: /imu/accelerometer
#    imu1_config: [
#      false, false, false,  # x, y, z
#      false, false, false,  # roll, pitch, yaw
#      false, false, false,  # v_x, v_y, v_z
#      false, false, false,  # v_roll, v_pitch, v_yaw
#      true,  true,  true,   # a_x, a_y, a_z
#    ]
#    imu1_differential: false
#    imu1_relative: true
#    imu1_queue_size: 5
#    imu1_pose_rejection_threshold: 0.8                 # Note the difference in parameter names
#    imu1_twist_rejection_threshold: 0.8                #
#    imu1_linear_acceleration_rejection_threshold: 0.8  #
#
#    # [ADVANCED] Some IMUs automatically remove acceleration due to gravity, and others don't. If yours doesn't, please set
#    # this to true, and *make sure* your data conforms to REP-103, specifically, that the data is in ENU frame.
#    imu1_remove_gravitational_acceleration: true

    use_control: false

    process_noise_covariance: [  # diagonal of the process noise covariance matrix
      0.2, 0.2, 1e-3,  # x, y, z
      0.3, 0.3, 0.1,   # roll, pitch, yaw
      0.5, 0.5, 0.1,   # v_x, v_y, v_z
      0.3, 0.3, 0.3,   # v_roll, v_pitch, v_yaw
      0.3, 0.3, 0.3    # a_x, a_y, a_z
    ]

# For parameter descriptions, see https://github.com/cra-ros-pkg/robot_localization/blob/ros2/params/navsat_transform.yaml
navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 3.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_cartesian_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false
    datum: [45.92025666666667, 9.321055, 0.0]
