!!python/object:spraying_task_plan.SprayingTaskPlan
task_plan_items:
- !!python/object:spraying_task_plan.TaskPlanItem
  behavior_tree_name: spraying_task_navigate_through_poses_approach.xml
  item_id: approach_1
  nav_path: []
  nav_timeout: 10.0
  result: null
- !!python/object:spraying_task_plan.TaskPlanItem
  behavior_tree_name: spraying_task_navigate_through_poses_row.xml
  item_id: row_1
  nav_path: []
  nav_timeout: null
  result: null