map_frame: apple_orchard

positioning_approach_planner_id: GridBased
positioning_approach_controller_id: FollowPath
positioning_approach_goal_checker_id: asb_goal_checker
positioning_approach_progress_checker_id: simple_progress_checker
max_positioning_navigation_attempts: 3

straight_approach_controller_id: FollowPath
straight_approach_goal_checker_id: asb_curvature_arc_goal_checker
straight_approach_progress_checker_id: simple_progress_checker
max_straightening_navigation_attempts: 3

row_path_controller_id: FollowStraightPath
row_path_goal_checker_id: asb_goal_checker
row_path_progress_checker_id: simple_progress_checker

path_pose_distance: 0.1

alternate_rows: False
switch_direction: False

row_path_external_dist: 2.0  # distance of inter-row path from row when navigating on the outside (as opposed to between two rows)
row_path_margin: 0.5  # distance of the positioning pose to the beginning of the rows
row_approach_margin: -0.5  # distance between the straightening and positioning approach pose

fan_velocity_target_rpm: 1200
fan_velocity_threshold_rpm: 800
max_canopy_width: 2.0
canopy_roi_x_1: -0.25
canopy_roi_x_2: 0.25

hectare_ref_volume: 168.0  # [L] amount of liquid to spray per hectare for a vineyard/orchard of given inter_row and with a uniform canopy depth equal to canopy_ref_depth
inter_row: 4.0
canopy_ref_depth: 1.2

canopy_layer_bounds: [0.35, 0.65, 0.95, 1.25, 1.55, 1.85, 2.15]

rows:
#  - row_id: row_1
#    frame_id: apple_orchard
#    start_point:
#      x: 0.6
#      y: -1.87
#    end_point:
#      x: 105.23
#      y: -2.18
#  - row_id: row_2
#    frame_id: apple_orchard
#    start_point:
#      x: -1.11  # fixed
#      y: -5.89
#    end_point:
#      x: 107.15  # fixed
#      y: -5.92
#  - row_id: row_3
#    frame_id: apple_orchard
#    start_point:
#      x: -1.36  # fixed
#      y: -9.91
#    end_point:
#      x: 107.58  # fixed
#      y: -10.08
#  - row_id: row_4
#    frame_id: apple_orchard
#    start_point:
#      x: -0.09
#      y: -13.87
#    end_point:
#      x: 106.37
#      y: -13.91
#  - row_id: row_5
#    frame_id: apple_orchard
#    start_point:
#      x: -0.38
#      y: -17.86
#    end_point:
#      x: 106.69
#      y: -18.04
#  - row_id: row_6
#    frame_id: apple_orchard
#    start_point:
#      x: -0.63
#      y: -21.87
#    end_point:
#      x: 107.1
#      y: -22.02
#  - row_id: row_7
#    frame_id: apple_orchard
#    start_point:
#      x: -0.9
#      y: -25.91
#    end_point:
#      x: 107.39
#      y: -25.93
#  - row_id: row_8
#    frame_id: apple_orchard
#    start_point:
#      x: -1.13
#      y: -29.82
#    end_point:
#      x: 107.69
#      y: -30.09
#  - row_id: row_9
#    frame_id: apple_orchard
#    start_point:
#      x: -1.39
#      y: -33.81
#    end_point:
#      x: 108.08
#      y: -34.11
  - row_id: row_10
    frame_id: apple_orchard
    start_point:
      x: -3.13  # fixed
      y: -37.8
    end_point:
      x: 110.02  # fixed
      y: -38.0
#  - row_id: row_11
#    frame_id: apple_orchard
#    start_point:
#      x: -3.33  # fixed
#      y: -41.78
#    end_point:
#      x: 110.38  # fixed
#      y: -41.94
