# For some reason, the costmap obstacle layers do not work correctly when publishing the laser scan messages
# in the base_footprint frame, so we need to publish them in base_link.
# base_link is 0.2 m above base_footprint (defined in asb_ros2_control/description/urdf/asb_description.urdf.xacro)

lidar_filter_front:
  ros__parameters:
    base_frame_id: base_link
    x_min: -1.3
    x_max: +0.9
    y_min: -0.85
    y_max: +0.85
    z_min: -0.3
    z_max: +2.2
    scan_min_height: 0.1
    scan_max_height: 2.5

lidar_filter_rear:
  ros__parameters:
    base_frame_id: base_link
    x_min: -1.3
    x_max: +0.9
    y_min: -0.85
    y_max: +0.85
    z_min: -0.3
    z_max: +2.2
    scan_min_height: 0.1
    scan_max_height: 2.5
