lidar_filter_front:
  ros__parameters:
    base_frame_id: base_link
    x_min: -1.3
    x_max: +0.9
    y_min: -1.0
    y_max: +1.0
    z_min: -0.3
    z_max: +2.2
    scan_min_height: 0.5
    scan_max_height: 2.5

lidar_filter_rear:
  ros__parameters:
    base_frame_id: base_link
    x_min: -1.3
    x_max: +0.9
    y_min: -1.0
    y_max: +1.0
    z_min: -0.3
    z_max: +2.2
    scan_min_height: 0.5
    scan_max_height: 2.5