lidar_filter_front:
  ros__parameters:

    apply_range_min_filter: true
    range_min: 0.3

    apply_range_max_filter: false
    range_max: 10.0

    apply_box_filter: true
    frame_id: base_footprint
    x_min: -1.3
    x_max: +0.8
    y_min: -1.0
    y_max: +1.0
    z_min: +0.0
    z_max: +2.4