asb_webots_robot:
  ros__parameters:
    sim_state_topic : /system_test/state
    sim_state_cmd_topic : /system_test/state_cmd

    ground_truth_position_topic: /ground_truth_position
    ground_truth_position_frame_id: map

    gnss_1_topic: /gnss_1/llh_position
    gnss_1_frame_id: gnss_1_link  # in the real robot, the NavSatFix message refers to the frame of the antenna 1 published by the microstrain driver
    gnss_2_topic: /gnss_2/llh_position
    gnss_2_frame_id: gnss_2_link  # in the real robot, the NavSatFix message refers to the frame of the antenna 2 published by the microstrain driver
    gnss_update_rate: 1.0
    gnss_covariance_diagonal: [0.2, 0.2, 0.2]

    # The (simulated) inertial unit publishes the angular position measurement.
    # In the real robot, this data is computed by the EKF filter of the GQ7 sensor with the IMU and dual antenna GNSS compassing.
    # TODO rename topic, it's not really an odometry
    inertial_unit_topic: /ekf/odometry_map
    inertial_unit_parent_frame_id: map
    inertial_unit_child_frame_id: inertial_link  # in the real robot, this message refers to the imu_link frame
    inertial_unit_update_rate: 10.0
    inertial_unit_covariance_diagonal: [0.2, 0.2, 0.2]

    # The (simulated) imu publishes the angular velocity measurement.
    # In the real robot, this is data is measured by the gyroscope of the GQ7 sensor.
    imu_topic: /imu
    imu_update_rate: 100.0
    imu_frame_id: imu_link
    gyro_frame_id: gyro_link
    gyro_covariance_diagonal: [0.1, 0.1, 0.1]
