controller_server:
  ros__parameters:
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.3
    min_y_velocity_threshold: 0.0
    min_theta_velocity_threshold: 0.0
    failure_tolerance: 0.3
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 30.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      stateful: True
      xy_goal_tolerance: 0.3
      yaw_goal_tolerance: 0.2
    FollowPath:
      plugin: "asb_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      transform_tolerance: 0.1
      allow_reversing: true
      desired_linear_vel: 0.5
      lookahead_dist: 0.4
      max_robot_pose_search_dist: 10.0
      min_approach_linear_velocity: 0.2
      approach_velocity_scaling_dist: 0.1
      max_allowed_time_to_collision_up_to_carrot: 2.0
      use_cost_regulated_linear_velocity_scaling: false  # Reduces velocity near obstacles TODO set true
      regulated_linear_scaling_min_speed: 0.25
      cost_scaling_dist: 0.3
      cost_scaling_gain: 1.0
      inflation_cost_scaling_factor: 3.0
      use_collision_detection: true
      use_interpolation: true
      use_velocity_scaled_lookahead_dist: false
      use_regulated_linear_velocity_scaling: false  # Reduces velocity based on curvature
      use_fixed_curvature_lookahead: false
      use_rotate_to_heading: false
#      regulated_linear_scaling_min_radius: 0.9
#      min_lookahead_dist: 0.3
#      max_lookahead_dist: 0.5
#      lookahead_time: 1.5
#      rotate_to_heading_angular_vel: 0.0
#      curvature_lookahead_dist: 1.0
#      rotate_to_heading_min_angle: 0.785
#      max_angular_accel: 3.2
