controller_server:
  ros__parameters:
    controller_frequency: 20.0

    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      stateful: True
      xy_goal_tolerance: 0.3
      yaw_goal_tolerance: 0.2

    AckermannConstraints:
      min_turning_r: 1.0

    controller_plugins: [ "FollowPath" ]
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 56
      model_dt: 0.05
      batch_size: 2000
      vx_std: 0.2
      vy_std: 0.2
      wz_std: 1.0
      vx_max: 0.5
      vx_min: -0.5
      vy_max: 0.0
      wz_max: 0.5
      iteration_count: 1
      prune_distance: 1.7
      transform_tolerance: 0.1
      temperature: 0.3
      gamma: 0.015

      enforce_path_inversion: true
      inversion_xy_tolerance: 0.3
      inversion_yaw_tolerance: 0.3

      motion_model: "Ackermann"
      visualize: true
      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3
      critics: [
        "ConstraintCritic",
        "GoalCritic",
        "GoalAngleCritic",
        "PathAlignCritic",
        "PathFollowCritic",
        "PathAngleCritic",
#        "PreferForwardCritic",
#        "ObstaclesCritic",
      ]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 0.1
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 0.1
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 10.0
        offset_from_furthest: 5
        threshold_to_consider: 0.1
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        max_path_occupancy_ratio: 0.05
        threshold_to_consider: 0.1
        offset_from_furthest: 20
        use_path_orientations: true
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 4
        threshold_to_consider: 0.1
        max_angle_to_furthest: 1.0
        mode: 2  # 0: FORWARD_PREFERENCE, 1: NO_DIRECTIONAL_PREFERENCE, 2: CONSIDER_FEASIBLE_PATH_ORIENTATIONS
#      PreferForwardCritic:
#        enabled: true
#        cost_power: 1
#        cost_weight: 5.0
#        threshold_to_consider: 0.5
#      ObstaclesCritic:
#        enabled: true
#        cost_power: 1
#        repulsion_weight: 1.5
#        critical_weight: 20.0
#        consider_footprint: true
#        collision_cost: 10000.0
#        collision_margin_distance: 0.1
#        near_goal_distance: 0.5
