controller_server:
  ros__parameters:
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.01
    min_y_velocity_threshold: 0.0
    min_theta_velocity_threshold: 0.01
    failure_tolerance: 0.3
    progress_checker_plugins: ["simple_progress_checker"]
    goal_checker_plugins: ["asb_goal_checker"]
    controller_plugins: ["FollowPath", "FollowStraightPath"]

    simple_progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 30.0
    asb_goal_checker:
      plugin: "asb_nav2_plugins::ASBGoalChecker"
      xy_goal_tolerance: 0.2
      yaw_goal_tolerance: 0.1

    FollowPath:
      plugin: "asb_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      transform_tolerance: 0.1
      allow_reversing: true
      min_turning_radius: 1.5
      desired_linear_vel: 0.6
      lookahead_dist: 1.0
      use_adaptive_lookahead_dist: true
      adaptive_lookahead_path_distance_margin: 0.3
      max_robot_path_dist: 0.3
      max_robot_pose_search_dist: 10.0
      min_approach_linear_velocity: 0.4
      approach_velocity_scaling_dist: 0.5
      max_allowed_time_to_collision_up_to_carrot: 2.0
      regulated_linear_scaling_min_speed: 0.25
      cost_scaling_dist: 0.3
      cost_scaling_gain: 1.0
      inflation_cost_scaling_factor: 3.0
      use_collision_detection: true
      use_interpolation: true

      use_goal_angle_approach: true
      goal_angle_approach_dist: 1.0
      use_goal_angle_at_cusp: true
      goal_angle_cusp_dist: 1.0

      use_cost_regulated_linear_velocity_scaling: false  # Reduces velocity near obstacles TODO set true

      use_regulated_linear_velocity_scaling: false  # Reduces velocity based on curvature from desired_linear_vel when the current turning radius is regulated_linear_scaling_min_radius or above, to 0 when the current turning radius is 0 (linearly)
      regulated_linear_scaling_min_radius: 3.0

      # unused features
      use_velocity_scaled_lookahead_dist: false
      use_fixed_curvature_lookahead: false
      use_rotate_to_heading: false

      # unused features params
#      min_lookahead_dist: 0.3
#      max_lookahead_dist: 0.5
#      lookahead_time: 1.5
#      rotate_to_heading_angular_vel: 0.0
#      curvature_lookahead_dist: 1.0
#      rotate_to_heading_min_angle: 0.785
#      max_angular_accel: 3.2

    FollowStraightPath:
      plugin: "asb_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      transform_tolerance: 0.1
      allow_reversing: true
      min_turning_radius: 1.7
      desired_linear_vel: 1.1
      lookahead_dist: 2.8
      use_adaptive_lookahead_dist: true
      adaptive_lookahead_path_distance_margin: 0.3
      max_robot_path_dist: 1.0
      max_robot_pose_search_dist: 10.0
      min_approach_linear_velocity: 0.4
      approach_velocity_scaling_dist: 0.5
      max_allowed_time_to_collision_up_to_carrot: 2.0
      regulated_linear_scaling_min_speed: 0.25
      cost_scaling_dist: 0.3
      cost_scaling_gain: 1.0
      inflation_cost_scaling_factor: 3.0
      use_collision_detection: false  # [!]
      use_interpolation: true
      use_goal_angle_approach: true
      goal_angle_approach_dist: 0.4

      use_cost_regulated_linear_velocity_scaling: false  # Reduces velocity near obstacles TODO set true

      use_regulated_linear_velocity_scaling: false  # Reduces velocity based on curvature from desired_linear_vel when the current turning radius is regulated_linear_scaling_min_radius or above, to 0 when the current turning radius is 0 (linearly)
      regulated_linear_scaling_min_radius: 3.0

      # unused features
      use_velocity_scaled_lookahead_dist: false
      use_fixed_curvature_lookahead: false
      use_rotate_to_heading: false

      # unused features params
#      min_lookahead_dist: 0.3
#      max_lookahead_dist: 0.5
#      lookahead_time: 1.5
#      rotate_to_heading_angular_vel: 0.0
#      curvature_lookahead_dist: 1.0
#      rotate_to_heading_min_angle: 0.785
#      max_angular_accel: 3.2
